---
title: "Red Wine Quality"
author: "Valli Kasivishwanath"
date: "2023-11-28"
output:
  pdf_document: default
  pdf document: default
---

```{r setup, echo=FALSE, message=F, warning=F}
#==============================================================================
#   Every assignment Chunk
#==============================================================================

  # Clear the working space
    rm(list = ls())


# Set working directory
setwd("/Users/ashwin/Desktop/Chintu MS /Quarter 1/Econ Wine Project")  
#getwd()


### Load the packages (all must have been installed)
    library(tidyverse)
    library(doBy)
    library(foreign)
    library(knitr)
    library(lmtest)
    library(readstata13)
    library(sandwich)
    library(stargazer)
    library(AER)
    library(gdata)
    library(wooldridge)
    library(openintro)
    library(readxl)
    library(car)
    
# This is the function we use to adjust the errors when we have heteroskedastic data.
cse=function(reg) {
    rob=sqrt(diag(vcovHC(reg, type="HC1")))
    return(rob)
    }
```

**DESCRIPTIVE STATISTICS OF RED WINE QUALITY**
```{r Data, echo=FALSE, message=FALSE, warning=FALSE, comment=""}
# Read the data from the CSV file
data <- read.csv("winequality.csv")

# columns for analysis
selected_cols <- c( "alcohol", "volatile.acidity","pH", "sulphates", "residual.sugar", "total.sulfur.dioxide","fixed.acidity","citric.acid","chlorides","free.sulfur.dioxide","density")

# Check for NA values in the selected columns
missing_values <- apply(data[selected_cols], 2, function(x) sum(is.na(x)))

# Remove rows with missing values in any of the selected columns
data_cleaned <- na.omit(data[selected_cols])


stargazer(data_cleaned, type = "text", digits = 2, 
          summary.stat = c("n", "mean", "median", "sd"), 
          title = "Descriptive Statistics of Red Wine Quality", 
          column.labels = c( "alcohol", "volatile.acidity", "pH", "sulphates", "residual.sugar", "total.sulfur.dioxide","fixed.acidity","citric.acid","chlorides","free.sulfur.dioxide","density"))
```

**HISTOGRAM OF ALCOHOL AND QUALITY**
```{r hist, echo=FALSE, message=F, warning=FALSE, comment="",include=TRUE}
# Create a histogram of variable alcohol. 
ggplot(data) + geom_histogram(aes(x = alcohol), col = "blue", binwidth = 0.5) + 
  labs(title = "Red Wine Quality With Alcohol", x = "Alcohol", y = "Count")
```

**SCATTERPLOT FOR ALCOHOL VS QUALITY**
```{r scatterp, echo=FALSE, message=FALSE, warning=FALSE, comment=""}
ggplot(data, aes(x=alcohol, y=quality)) + geom_point(col="blue") + 
        labs(title = "Alcohol vs Quality ", x = "Alcohol", y = "Quality") +
        stat_smooth(method=lm, col = "red", se=FALSE) 
```

**SCATTERPLOT FOR VOLATILE ACIDITY VS QUALITY**
```{r scatterp1, echo=FALSE, message=FALSE, warning=FALSE, comment=""}
ggplot(data, aes(x=volatile.acidity, y=quality)) + geom_point(col="blue") + 
        labs(title = "Volatile Acidity vs Quality ", x = "Volatile Acidity", y = "Quality") +
        stat_smooth(method=lm, col = "red", se=FALSE) 
```

**SCATTERPLOT FOR SULPHATES VS QUALITY**
```{r scatterp2, echo=FALSE, message=FALSE, warning=FALSE, comment=""}
ggplot(data, aes(x=sulphates, y=quality)) + geom_point(col="blue") + 
        labs(title = "Sulphates vs Quality ", x = "Sulphates", y = "Quality") +
        stat_smooth(method=lm, col = "red", se=FALSE) 
```

**BASE REGRESSION ANALYSIS ON QUALITY**
```{r graph, echo=FALSE, message=FALSE, warning=FALSE, comment=""}

# Regression 1: Alcohol on quality
regr1 <- lm(quality ~ alcohol, data = data)

# Regression 2: Alcohol,volatile acidity on Quality
regr2 <- lm(quality  ~ alcohol+ volatile.acidity, data = data)

# Regression 3: Alcohol,volatile acidity ,sulphates on Quality
regr3 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates, data = data)

# Regression 4: Alcohol,volatile acidity ,sulphates ,Residual Sugar on Quality
regr4 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar, data = data)

# Regression 5: Alcohol,volatile acidity ,sulphates ,Residual Sugar,total.sulfur.dioxide on Quality
regr5 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide, data = data)

# Regression 6: Alcohol,volatile acidity ,sulphates ,Residual Sugar,total.sulfur.dioxide,free.sulfur.dioxide on Quality
regr6 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide, data = data)

# Regression 7: Alcohol,volatile acidity ,sulphates ,Residual Sugar,total.sulfur.dioxide,free.sulfur.dioxide,fixed.acidity on Quality
regr7 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide + fixed.acidity , data = data)

# Display all regressions in one stargazer table
lm <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide + fixed.acidity , data = data)
stargazer(regr1, regr2,regr3, regr4,regr5,regr6,regr7,
          se=list(cse(regr1),cse(regr2),cse(regr3),cse(regr4),cse(regr5),cse(regr6),cse(regr7)),
    title= 'Regression Analysis: Effect of Variables on Quality', type="text", 
    star.cutoffs=NA, df=FALSE, digits=3)
``` 

**LINEAR HYPOTHESIS TEST**
```{r hypothesis test, echo=FALSE, message=FALSE, warning=FALSE, comment=" "}
# Hypothesis test using lht command  
full_model <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide + fixed.acidity, data = data)
lht(full_model,c("sulphates = 0","fixed.acidity = 0"),white.adjust="hc1")
```

**ALTERNATIVE REGRESSION ANALYSIS**
```{r interaction,echo=FALSE, message=FALSE, warning=FALSE, comment=""}

# Assuming your model is already fit as specified
model1 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide + fixed.acidity , data = data)

model2 <- lm(quality  ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide + fixed.acidity + alcohol:sulphates, data = data)

stargazer(model1,model2, se=list(cse(model1),cse(model2)),
    title= 'Regression Analysis: Interaction Model of Alcohol and sulphates', type="text", 
    star.cutoffs=NA, df=FALSE, digits=3)

```

```{r hypothesis 3, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, comment=""}

# Hypothesis test using lht command  

restricted_model <- lm(quality ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide+fixed.acidity, data = data)
unrestricted_model <- lm(quality ~ alcohol+ volatile.acidity + sulphates + residual.sugar + total.sulfur.dioxide + free.sulfur.dioxide+fixed.acidity+alcohol:sulphates, data = data)
lht(unrestricted_model,c("alcohol:sulphates = 0"),white.adjust="hc1")
```
